
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "veegoxchain-node1"
    static_configs:
      - targets: ["veegoxchain-node1:9090"]
    metrics_path: /debug/metrics/prometheus

  - job_name: "veegoxchain-node2"
    static_configs:
      - targets: ["veegoxchain-node2:9090"]
    metrics_path: /debug/metrics/prometheus

  - job_name: "veegoxchain-node3"
    static_configs:
      - targets: ["veegoxchain-node3:9090"]
    metrics_path: /debug/metrics/prometheus
