// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsqxomuotkfpbabtzzdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzcXhvbXVvdGtmcGJhYnR6emRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMzYzMTQsImV4cCI6MjA2MjYxMjMxNH0.ktYlLbJRlqkRiH9_2mkAb4UsydjlhgC8kxHYSRhJS_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);